---
# Defines tasks applicable for NTP (Network Time Protocol)

- name: Install ntp
  ansible.builtin.package:
    name: ntp
    state: present
  tags:
    - dependencies

- name: Configure ntp
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0640
  notify:
    - Restart ntp

- name: Ensure ntpd is running
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes
